/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Test;
import java.sql.*;  
import java.sql.Connection;  
import java.sql.DriverManager;  
import javax.swing.JOptionPane;

import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;

import java.io.*;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;


import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

 
import  org.apache.poi.hssf.usermodel.HSSFSheet;
import  org.apache.poi.hssf.usermodel.HSSFWorkbook;
import  org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook; 
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.Date;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.lang.Thread;
import java.io.PrintWriter; 

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;


/**
 *
 * @author daniel
 */

public class interfaz extends javax.swing.JFrame {




    /**
     * Creates new form interfaz
     */
    public interfaz() {

        initComponents();

        /******************************************************************************/

        
           //BufferedImage bi = ImageIO.read(new File("utils/Logo_3.png.png"));

        //ImageIcon imgicon = new ImageIcon("utils/Logo_3.png.png");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_pendientes = new javax.swing.JRadioButton();
        rb_pagadas = new javax.swing.JRadioButton();
        rb_pagadas_retenciones = new javax.swing.JRadioButton();
        rb_informe_pendientes = new javax.swing.JRadioButton();
        rb_informe_pagadas = new javax.swing.JRadioButton();
        rb_informe_pendientes_2 = new javax.swing.JRadioButton();
        rb_informe_pagadas_2 = new javax.swing.JRadioButton();
        rb_informe_retenciones = new javax.swing.JRadioButton();
        btn_generar = new javax.swing.JButton();
        lb_1 = new javax.swing.JLabel();
        lb_2 = new javax.swing.JLabel();
        lb_3 = new javax.swing.JLabel();
        lb_4 = new javax.swing.JLabel();
        panel_1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de reportes");
        setResizable(false);

        ImageIcon img = new ImageIcon("utils/Logo_3.png");
        setIconImage(img.getImage());

        rb_pendientes.setText("Pendientes");

        rb_pagadas.setText("Pagadas");

        rb_pagadas_retenciones.setText("Pagadas (retenciones)");

        rb_informe_pendientes.setText("Pendiente por Partida");

        rb_informe_pagadas.setText("Pagada por Partida");

        rb_informe_pendientes_2.setText("Pendiente por Grupo");

        rb_informe_pagadas_2.setText("Pagada por Grupo");

        rb_informe_retenciones.setText("Retencion directa");

        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        lb_1.setText("...");

        lb_2.setText("...");

        lb_3.setText("...");

        lb_4.setText("...");

        panel_1.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_generar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_pendientes)
                            .addComponent(rb_pagadas)
                            .addComponent(rb_pagadas_retenciones)
                            .addComponent(rb_informe_pendientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_informe_pagadas)
                            .addComponent(rb_informe_pendientes_2)
                            .addComponent(rb_informe_retenciones)
                            .addComponent(rb_informe_pagadas_2))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_1)
                    .addComponent(lb_3)
                    .addComponent(lb_2)
                    .addComponent(lb_4))
                .addContainerGap(210, Short.MAX_VALUE))
            .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_pendientes)
                            .addComponent(rb_informe_pagadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_pagadas)
                            .addComponent(rb_informe_pendientes_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_pagadas_retenciones)
                            .addComponent(rb_informe_pagadas_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_informe_pendientes)
                            .addComponent(rb_informe_retenciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_generar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_2)
                        .addGap(17, 17, 17)
                        .addComponent(lb_3)
                        .addGap(14, 14, 14)
                        .addComponent(lb_4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void result_consult(int res){
        if(res >= 0){
            //resultado ok
            panel_1.setBackground(new java.awt.Color(0, 255, 0));
            lb_2.setText("Consulta realizada");
            lb_3.setText("count: "+res);
            //lb_4.setText("...");
        }else if(res == -1){
            panel_1.setBackground(new java.awt.Color(155, 155, 155));
            lb_2.setText("Error guardando archivo..");
            //lb_3.setText("...");
            //lb_4.setText("...");
        }else if(res == -2){
            panel_1.setBackground(new java.awt.Color(255, 0, 0));
            lb_2.setText("No se pudo conectar!");
            //lb_3.setText("...");
            //lb_4.setText("...");
        }else{
            panel_1.setBackground(new java.awt.Color(255, 0, 0));
            lb_2.setText("Ha ocurrido un error.");
            //lb_3.setText("...");
            //lb_4.setText("...");
        }
    }


    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed

        consultas sg = new consultas();
        boolean filter = false;

        int res=-3;
        
       // JOptionPane.showMessageDialog(null, "Iniciando, esto puede tardar..");
        panel_1.setBackground(new java.awt.Color(255, 255, 51));
        lb_1.setText("Iniciando, esto puede tardar..");
        long startTime = System.currentTimeMillis();
        long endTime;
        if(rb_pagadas.isSelected() && !rb_pendientes.isSelected() && !rb_informe_pendientes.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_pagadas.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
           try{
                String sql = new utils().get_sql_pagadas("sql/pagadas.sql");
                res=sg.sql_pagadas(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql,new utils().check_filter());
                
           }catch(Exception ex){
                System.out.println(ex);
           }
        }else if(rb_pendientes.isSelected() && !rb_pagadas.isSelected() && !rb_informe_pendientes.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_pagadas.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
            try {
                //String content = new String(Files.readAllBytes(Paths.get("sql/pendientes.sql")));
                String sql = new utils().get_sql_pagadas("sql/pendientes.sql");
                res=sg.sql_pendientes(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql/*content*/,new utils().check_filter());
            }catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(rb_pagadas_retenciones.isSelected() && !rb_pendientes.isSelected() && !rb_pagadas.isSelected() && !rb_informe_pendientes.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_pagadas.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
            try {
                String sql = new utils().get_sql_pagadas("sql/pagadas_retenciones.sql");
                res=sg.pagadas_retenciones(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql);

            }catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(rb_informe_retenciones.isSelected() && !rb_pendientes.isSelected() && !rb_pagadas.isSelected() && !rb_informe_pendientes.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_pagadas.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
            try {
                String sql = new utils().get_sql_pagadas("sql/pagadas_retenciones.sql");
                res=new consultas_2().pagadas_retenciones2(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql);

            }catch (Exception ex) {
                System.out.println(ex);
            }
        }else if (rb_informe_pendientes.isSelected() && !rb_pendientes.isSelected() && !rb_pagadas.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_pagadas.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
            try {
                String content = new String(Files.readAllBytes(Paths.get("sql/pendientes2.sql")));
                res = new consultas_2().sql_pendientes(new utils().get_host(),new utils().get_name(),new utils().get_pass(),content,new utils().check_filter());
                
            }catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(rb_informe_pagadas.isSelected() && !rb_pagadas.isSelected() && !rb_pendientes.isSelected() && !rb_informe_pendientes.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
           try{
                String sql = new utils().get_sql_pagadas("sql/pagadas.sql");
                res=new consultas_2().sql_pagadas(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql,new utils().check_filter());

           }catch(Exception ex){
                System.out.println(ex);
           }
        }else if(rb_informe_pagadas_2.isSelected() && !rb_pagadas.isSelected() && !rb_pendientes.isSelected() && !rb_informe_pendientes.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes_2.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas.isSelected()){
           try{
                String sql = new utils().get_sql_pagadas("sql/pagadas.sql");
                res=new consultas_2().sql_pagadas2(new utils().get_host(),new utils().get_name(),new utils().get_pass(),sql,new utils().check_filter());

           }catch(Exception ex){
                System.out.println(ex);
           }
        }else if (rb_informe_pendientes_2.isSelected() && !rb_pendientes.isSelected() && !rb_pagadas.isSelected() && !rb_pagadas_retenciones.isSelected() && !rb_informe_pendientes.isSelected() && !rb_informe_pagadas.isSelected() && !rb_informe_retenciones.isSelected() && !rb_informe_pagadas_2.isSelected()){
            try {
                String content = new String(Files.readAllBytes(Paths.get("sql/pendientes2.sql")));
                res = new consultas_2().sql_pendientes2(new utils().get_host(),new utils().get_name(),new utils().get_pass(),content,new utils().check_filter());
                
            }catch (Exception ex) {
                System.out.println(ex);
            }
        }else{
            panel_1.setBackground(new java.awt.Color(255, 0, 0));
            lb_2.setText("Seleccione una consulta..");
        }
        result_consult(res);
        long time = ((System.currentTimeMillis() - startTime) / 1000);
        long minu = time / 60;
        String str="";
        if(time > 59){
            str = minu + " minutos";
        }else{
            str = time + " segundos";
        }
        lb_4.setText(str);
    }//GEN-LAST:event_btn_generarActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //interfaz sg = new interfaz();
                /*BufferedReader reader;
                String [] ln = new String[10];
                int count=0,res=0;
                String name=null;
                String pass=null;
                String host=null;
                try {
                    reader = new BufferedReader(new FileReader("connection/utils.txt"));
                    String line;

                    while ((line=reader.readLine())!= null) {
                        ln[count]=line;
                        count++;
                    }
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                for (int i=0; i<count;i++ ) {
                    String obj = ln[i].substring(0,1);
                    if(obj.equals("*")){
                        host = ln[i].replace("*","");
                        break;
                    }
                }
                name = ln[3];
                pass = ln[4];
                System.out.println("host: "+host);
                System.out.println("name: "+name);
                System.out.println("password: "+pass);*/
                //new interfaz().test_connection(c.get_host(),c.get_name(),c.get_pass());

    

                int res = new utils().test_connection(new utils().get_host(),new utils().get_name(),new utils().get_pass());
                if(res == 0){
                   
                }else{
                    JOptionPane.showMessageDialog(null, "Error conectando..");
                    System.exit(0);
                    //new interfaz().result_consult(-2);
                    //panel_1.setBackground(new java.awt.Color(255, 0, 0));
                    //lb_2.setText("No se pudo conectar!");
                }
          
                




               /* try {
                    String content = new String(Files.readAllBytes(Paths.get("sql/pendientes2.sql")));
                    res = new utils().test(new utils().get_host(),new utils().get_name(),new utils().get_pass(),content);
                }catch (Exception ex) {
                    System.out.println(ex);
                }
*/
                 //ImageIcon icon = new ImageIcon("utils/Logo_3.png.png");
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JRadioButton rb_informe_pendientes;
    private javax.swing.JRadioButton rb_pagadas_retenciones;
    private javax.swing.JRadioButton rb_informe_pendientes_2;
    private javax.swing.JRadioButton rb_informe_pagadas;
    private javax.swing.JRadioButton rb_informe_retenciones;
    private javax.swing.JRadioButton rb_informe_pagadas_2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_4;
    private javax.swing.JPanel panel_1;
    private javax.swing.JRadioButton rb_pagadas;
    private javax.swing.JRadioButton rb_pendientes;
    // End of variables declaration//GEN-END:variables
}
