------------*****ORDENES PENDIENTES POR PARTIDAS *****-------
---**********************************************************************--------
SELECT ANHO,ORGANISMO,FUENTE,PARTIDA,FONDO,ORDEN,ESTADO,CUENTA,BENEFICIARIO,FECHA_MODIFICACION,OBSERVACION,SUM(MONTO) MONTO  
FROM (
SELECT P.ANHO ANHO,
 	   P.PAGO_ID ORDEN,
	   P.RAZON_ID_FIN ESTADO,
	   SP.FECHA_MODIF FECHA_MODIFICACION,
   	   DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI) CUENTA,
	   DECODE(PA.AUTORIZADO_ID,NULL,PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF,PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI) BENEFICIARIO,	      
--	   P.FECHA_PAGO PAGADA,
	   UPPER(P.ORGA_ID||' - '||O.DENOMINACION) ORGANISMO,
	   UPPER(F.FFIN_ID||' - '||F.DENOMINACION) FUENTE,  
	   UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION) PARTIDA,
	   '' FONDO,
	   PA.OBSERVACION,
	   SUM(PI.MONTO_NETO) MONTO
FROM PAGO P, 
	 DET_PAGO_IMPUTADO PI, 
	 ORGANISMO O,
	 PLAN_UNICO_CTA PU, 
	 FUENTE_FINANCIAMIENTO F,
	 PAGO_IMPUTADO PA,
	 SEGUIMIENTO_PAGO SP   
WHERE P.PAGO_ID = PI.PAGO_ID
  AND P.ANHO = PI.ANHO
  AND P.ANHO=PU.ANHO
  AND P.ORGA_ID = PI.ORGA_ID 
  AND P.TIPG_ID = PI.TIPG_ID 
  AND P.ANHO=PA.ANHO
  AND P.ORGA_ID=PA.ORGA_ID
  AND P.PAGO_ID=PA.PAGO_ID
  AND P.TIPG_ID=PA.TIPG_ID
  AND P.ORGA_ID = O.ORGA_ID
  AND PI.PLUC_ID = PU.PLUC_ID  
  AND PI.FFIN_ID = F.FFIN_ID
  AND P.ANHO	= SP.ANHO 
  AND P.PAGO_ID	= SP.PAGO_ID 
  AND P.ORGA_ID	= SP.ORGA_ID 
  AND P.TIPG_ID = SP.TIPG_ID 
  AND P.RAZON_ID_FIN IN (0,1,2,3,5)    
  AND P.TIPG_ID IN (1,9,10)
  --AND P.ANHO IN (2022,2023)
  --AND TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
--  AND P.ORGA_ID=026
  AND Sp.segui_id = (SELECT MAX(segui_id)
                      FROM seguimiento_pago B
                     WHERE Sp.pago_id = b.pago_id
                       AND Sp.anho = b.anho
                       AND Sp.orga_id = b.orga_id
                       AND Sp.tipg_id = b.tipg_id)
AND TO_DATE(SP.FECHA_MODIF,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')----ESTA LINEA SE ACTIVA SI QUIEREN UNA FECHA EN ESPECIFICO, DE LO CONTRARIO DEJA COMENTADA. 			
GROUP BY P.ANHO,
	  	 P.PAGO_ID,
		  P.RAZON_ID_FIN,
	   SP.FECHA_MODIF,		  
	   DECODE(PA.AUTORIZADO_ID, NULL, PA.CTA_BANC_BENEF, PA.CTA_BANC_AUTORI),
	   DECODE(PA.AUTORIZADO_ID,NULL,PA.NOMBRE_BENEF||' '||PA.APELLIDO_BENEF,PA.NOMBRE_AUTORI||' '||PA.APELLIDO_AUTORI),	   	   
--		 P.FECHA_PAGO,
		 UPPER(P.ORGA_ID||' - '||O.DENOMINACION), 
		 UPPER(F.FFIN_ID||' - '||F.DENOMINACION),		 
		 UPPER(PU.PLUC_ID||' - '||PU.DENOMINACION), 
		 PA.OBSERVACION
--		 UPPER(F.FFIN_ID||' - '||F.DENOMINACION) 
UNION
SELECT P.ANHO PRESUPUESTO,
 	   P.PAGO_ID ORDEN,
	    P.RAZON_ID_FIN ESTADO,
	   SP.FECHA_MODIF FECHA_MODIFICACION,		
  	   DECODE(PNI.AUTORIZADO_ID, NULL, PNI.CTA_BANC_BENEF, PNI.CTA_BANC_AUTORI) CUENTA,	
	   DECODE(PNI.AUTORIZADO_ID,NULL,PNI.NOMBRE_BENEF||' '||PNI.APELLIDO_BENEF,PNI.NOMBRE_AUTORI||' '||PNI.APELLIDO_AUTORI) BENEFICIARIO,   
--	   P.FECHA_PAGO,
	   UPPER(P.ORGA_ID||' - '||O.DENOMINACION) ORGANISMO,
	   UPPER(F.FFIN_ID||' - '||F.DENOMINACION) FUENTE,	   
	   '' PARTIDA,  
	   UPPER(T.TIFO_ID||' - '||T.DENOMINACION) FONDO,       
	   PNI.OBSERVACION,
   	   SUM(PNI.MONTO_TOTAL) MONTO
FROM PAGO P, 
	 PAGO_NO_IMPUTADO PNI, 
	 ORGANISMO O, 
	 TIPO_FONDO T, 
	 FUENTE_FINANCIAMIENTO F,
	 SEGUIMIENTO_PAGO SP 
WHERE P.PAGO_ID = PNI.PAGO_ID
  AND P.ANHO = PNI.ANHO
  AND P.ORGA_ID = PNI.ORGA_ID 
  AND P.TIPG_ID = PNI.TIPG_ID
  AND P.ORGA_ID = O.ORGA_ID
  AND PNI.TIFO_ID = T.TIFO_ID
  AND PNI.FFIN_ID = F.FFIN_ID
  AND P.ANHO	= SP.ANHO 
  AND P.PAGO_ID	= SP.PAGO_ID 
  AND P.ORGA_ID	= SP.ORGA_ID 
  AND P.TIPG_ID = SP.TIPG_ID   
  AND P.TIPG_ID IN (1,9,10)
  --AND P.ANHO IN (2022,2023) 
  --AND TO_DATE(P.FECHA_PAGO,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')
--  AND P.ORGA_ID=026
  AND P.RAZON_ID_FIN IN (0,1,2,3,5)   
  AND Sp.segui_id = (SELECT MAX(segui_id)
                      FROM seguimiento_pago B
                     WHERE Sp.pago_id = b.pago_id
                       AND Sp.anho = b.anho
                       AND Sp.orga_id = b.orga_id
                       AND Sp.tipg_id = b.tipg_id)
AND TO_DATE(SP.FECHA_MODIF,'DD/MM/RRRR') BETWEEN TO_DATE(:PAR_DESDE,'DD/MM/RRRR') AND TO_DATE(:PAR_HASTA,'DD/MM/RRRR')----ESTA LINEA SE ACTIVA SI QUIEREN UNA FECHA EN ESPECIFICO, DE LO CONTRARIO DEJA COMENTADA.    
GROUP BY P.ANHO,
	  	 P.PAGO_ID,
		 P.RAZON_ID_FIN,
	     SP.FECHA_MODIF,
        DECODE(PNI.AUTORIZADO_ID, NULL, PNI.CTA_BANC_BENEF, PNI.CTA_BANC_AUTORI),	
		DECODE(PNI.AUTORIZADO_ID,NULL,PNI.NOMBRE_BENEF||' '||PNI.APELLIDO_BENEF,PNI.NOMBRE_AUTORI||' '||PNI.APELLIDO_AUTORI),	 
		 UPPER(P.ORGA_ID||' - '||O.DENOMINACION), 
		 UPPER(F.FFIN_ID||' - '||F.DENOMINACION),		 
		 UPPER(T.TIFO_ID||' - '||T.DENOMINACION),
    	 PNI.OBSERVACIOn		 		 
)
GROUP BY ANHO,ORGANISMO,FUENTE,PARTIDA,FONDO,ORDEN,ESTADO,CUENTA,BENEFICIARIO,FECHA_MODIFICACION,OBSERVACION
ORDER BY 1,2,3 ASC